### ISSUE TITLE
namaspace package in bsconfig

### ISSUE THREAD

**Issue by woeps** [jeddeloh/reason-apollo-client#3]
Awesome work you've done so far!!
Please consider nameapacing your package in bsconfig like:
```
  namespace: "Jeddeloh_ReasonApolloClient"
```

This could avoid potential naming collisions.

**Comment by jfrolich** [comment]
You generally don't have two apollo clients in one app, so why namespace? (not great for the user experience)

**Comment by jeddeloh** [comment]
@woeps, this was my initial inclination as well, but when considering this might be one of your first exposure points to reason, I've become convinced it's worth breaking some rules. However, I agree it would be nice to be following best practices here. Maybe we can have our cake and eat it too? I snuck in a `Jeddeloh__` prefix-namespaced root module with the template tag updates: https://github.com/jeddeloh/reason-apollo-client/pull/4/files#diff-202f2a3e8a02c2f878f0432a079f7381

The primary module is prefix-namespaced, but included in an `ApolloClient` module. In the case of a clash you still have access to the namespaced module. You could define your own `ApolloClient` module for that matter. In the case of clashing with `reason-apollo` for instance, I don't really care since this is intended to replace them completely, but I think you could just put `reason-apollo` earlier in the bs-dependencies if someone doing something crazy and couldn't avoid the clash?

Can anyone see any holes in this?

**Comment by jfrolich** [comment]
Since when is it best practice to prefix modules with the username? Doesn't sound like a good idea, it's just noise, and not user friendly at all to type all that. Just come up with a good unique name. There is no reason at all to have two modules with the name `ApolloClient` in your project.

**Comment by jfrolich** [comment]
> The primary module is prefix-namespaced, but included in an `ApolloClient` module. In the case of a clash you still have access to the namespaced module. You could define your own `ApolloClient` module for that matter. In the case of clashing with `reason-apollo` for instance, I don't really care since this is intended to replace them completely, but I think you could just put `reason-apollo` earlier in the bs-dependencies if someone doing something crazy and couldn't avoid the clash?

Sounds like a good approach, but don't you think if there is a clash it doesn't compile?

**Comment by woeps** [comment]
I'm sure the most common use case is already covered as is: If you want an ApolloClient, just pick one and use that. But there are still possibilities, where you might want 2 different bindings for the same thing. Even if this is just for migration.

At least I see namespacing as a best practice and I also heared it several times in the community. The bsb docs also state the recommendation to use it.

Furthermore I do understand to not namespace in favor of a better / easier user experience while not supporting some edge cases with naming collisions. The probability of having duplicate module names is higher for bindings, than for a uniquely named library.
I wanted to make sure not namespacing the package was a deliberate decision and furthermore understan the reasoning behind that.

**Comment by jfrolich** [comment]
Yes it was deliberate. For the reason that most published packages are not namespace atm. Once they fix the problem that you can't have anything on the main module (so everything is two modules deep) it becomes feasible (worth it). For the rest every module is prepended by name, so that should be good enough.

**Comment by jfrolich** [comment]
> Edit: I haven't tested, but if the second module with the same name in bs-dependencies just shadows the first I think yout approach @jeddeloh provides excellent balance of user experience and having an eacapr hatch in case of a collision!

Great! I still think this is a bit overthinking situations that don't really exists in the real world, but at least this is a solution :)

**Comment by jeddeloh** [comment]
> Edit: I haven't tested, but if the second module with the same name in bs-dependencies just shadows the first, I think your approach @jeddeloh provides excellent balance of user experience and having an escape hatch in case of a collision!

I'm just now realizing, I don't know which direction "shadow" as a verb works here 🤣 In any case, you will have access to the first one defined in bs-dependencies and not the second. There's no compiler errors unless you're trying to access stuff on the second module.

> Great! I still think this is a bit overthinking situations that don't really exists in the real world, but at least this is a solution :)

For some reason, I like being able to create my _own_ `ApolloClient.re` module that has my client bundled up with all the methods and refinements I've added on top of the base library. This method frees up that possibility. So while ridiculous, it's another small bonus of this approach. 

I'm going to close this issue unless people have more to say.  @woeps @jfrolich Thanks so much for the input!

**Comment by jfrolich** [comment]
> For some reason, I like being able to create my _own_ `ApolloClient.re` module that has my client bundled up with all the methods and refinements I've added on top of the base library. This method frees up that possibility. So while ridiculous, it's another small bonus of this approach.

Yeah that is a nice use-case.

**Comment by jeddeloh** [comment]
Resolved with prefix-namespaced root module in #4
